### ISSUE TITLE
ipfs that seem to work

### ISSUE THREAD

**Issue by laszloekovacs** [laszloekovacs/airsoft-org#32]
```
services:
  ipfs:
    image: ipfs/kubo:latest
    volumes:
      # IPFS data
      - data_file:/data/ipfs

    ports:
      # P2P TCP/QUIC transports
      - "4001:4001"
      - "4001:4001/udp"
      # Gateway
      - "8080:8080"
      # RPC API (Do not expose this port to public internet)
      - "5001:5001"
volumes:
  data_file:
```
